Update trash

diff --git a/functions/trash b/functions/trash
--- a/functions/trash
+++ b/functions/trash
@@ -1,32 +1,30 @@
 #!/bin/zsh
-##? trash - Move files to macOS trash
+##? trash - Moves files to macOS trash.
+
+# function trash {
+
 emulate -L zsh
 setopt local_options extended_glob
 
-if (( $# == 0 )); then
-  echo >&2 "Usage: trash <files>"
-  return 1
-fi
-
-if [[ $OSTYPE != darwin* ]]; then
-  print -ru2 -- "trash: macOS not detected."
-  return 1
-fi
-
 local file
-local -a files
+local -a files=()
 for file in $@; do
   if [[ -e $file ]]; then
-    files+=("the POSIX file \"${file:A}\"")
+    # ':a' gets the full path (do not use ':A', which would resolve symlinks)
+    files+=("the POSIX file \"${file:a}\"")
   else
-    print -ru2 -- "trash: No such file or directory '$file'."
+    print "trash: No such file or directory '$file'." >&2
     return 1
   fi
 done
 
 if (( $#files == 0 )); then
-  print -ru2 -- 'usage: trash <files...>'
-  return 64 # match rm's return code
+  print 'usage: trash <files...>' >&2
+  return 64  # Match rm's return code.
 fi
 
-osascript 2>&1 >/dev/null -e "tell app \"Finder\" to move { "${(pj., .)files}" } to trash"
+# Join file list with commas, and tell Finder to trash that list.
+local file_list="${(pj., .)files}"
+osascript 2>&1 > /dev/null -e "tell app \"Finder\" to move { "${file_list}" } to trash"
+
+# }
